# Hardware gate; run under julia_metal. --generate explicitly regenerates the
# compile-only inventory after a reviewed engine/dependency change. Ordinary
# test runs never update it. There is no instrumentation in production code.
using Test, JSON
using BeatEngineCompiledMetalBundle
import Metal

const Bundle = BeatEngineCompiledMetalBundle

function observed_metal_signatures()
    observed = Set{Tuple{Any,Any}}()
    function observe(job)
        types = job.source.specTypes.parameters
        push!(observed, (types[1].instance, Tuple{types[2:end]...}))
    end
    # Metal 1.11.1 forces compilation through this debug hook even when device
    # code was loaded from a pkgimage. Clearing only kernel instances makes the
    # hook see each launch signature without altering portable cache contents.
    empty!(Metal.kernel_instances)
    Base.ScopedValues.with(Metal.GPUCompiler.compile_hook => observe) do
        mktempdir() do directory
            tiny = joinpath(directory, "tiny.msh")
            write(tiny, Bundle.WORKLOAD_MESH_OFF)
            fixtures = joinpath(@__DIR__, "..", "test_meshes")
            for (symmetry, mesh, scale) in (
                ("off", tiny, 1.0),
                ("off", joinpath(fixtures, "sample.msh"), 0.001),
                ("x", joinpath(fixtures, "sample_half.msh"), 0.001),
                ("xy", joinpath(fixtures, "sample_quarter.msh"), 0.001),
                ("ground", joinpath(fixtures, "sample.msh"), 0.001),
            )
                # Include the default fused path and the production operator
                # path used by coupled systems. Orders 1/2/4 cover the regular
                # triangle rule's one/three/six-point specializations.
                for assembly in ("direct_system", "operator_matrices"), order in (1, 2, 4)
                    request = Bundle.workload_request(mesh, symmetry)
                    request["frequencies_hz"] = [1000.0, 2000.0]
                    request["outputs"][1]["options"]["points_m"] =
                        [[2sin(a), symmetry == "ground" ? 0.3 : 0.0, 2cos(a)]
                         for a in range(0, pi; length=37)]
                    system = request["compiled_system"]
                    system["meshes"][1]["scale_to_m"] = scale
                    # The compiled ground contract rejects a face coplanar
                    # with Y=0. Raise the full fixture before its image solve.
                    if symmetry == "ground"
                        system["meshes"][1]["translation_m"] = [0.0, 0.3, 0.0]
                    end
                    port = deepcopy(only(system["excitation_ports"]))
                    port["id"] = "port:second"
                    push!(system["excitation_ports"], port)
                    request["excitation_port_ids"] = ["port:source", "port:second"]
                    request["solver_options"] = merge(Dict{String,Any}(request["solver_options"]), Dict(
                        "bem_backend" => "metal", "quadrature_order" => order,
                        "regular_quadrature_mode" => "fixed",
                        "burton_miller_assembly" => assembly))
                    # Match JSON decoding at the worker boundary.
                    request = JSON.parse(JSON.json(request))
                    outcome = redirect_stdout(devnull) do
                        Bundle.solve_request(request; event_mode=true)
                    end
                    @test !outcome.cancelled
                    @test outcome.solved_count == 2
                end
            end
        end
    end
    return observed
end

function write_metal_signatures(path, signatures)
    lines = String[]
    for (f, tt) in signatures
        line = "    (" * repr(typeof(f)) * ".instance, " * repr(tt) * "),"
        line = replace(line, r"(?<![.\w])GPUArrays\." => "Metal.GPUArrays.",
                             r"(?<![.\w])KernelAbstractions\." => "Metal.KernelAbstractions.")
        push!(lines, line)
    end
    open(path, "w") do io
        println(io, "# Generated by julia_local/tests/metal_kernel_coverage_tests.jl --generate.")
        println(io, "# Float32 compiled exterior requests; see the bundle README for coverage.")
        println(io, "[")
        foreach(line -> println(io, line), sort!(lines))
        println(io, "]")
    end
end

@testset "Metal compiled kernel signature coverage" begin
    # A hardware qualification must fail rather than pass a skipped workload.
    @test Metal.functional()
    observed = observed_metal_signatures()
    @test !isempty(observed)
    if "--generate" in ARGS
        path = joinpath(dirname(pathof(Bundle)), "MetalKernelSignatures.jl")
        write_metal_signatures(path, observed)
        @info "Generated BEAT Metal kernel inventory" signatures=length(observed)
    else
        expected = Set(Bundle.metal_kernel_signatures())
        missing = setdiff(observed, expected)
        for (f, tt) in missing
            @error "Production Metal kernel missing from precompile inventory" function_type=typeof(f) argument_types=tt
        end
        @test isempty(missing)
        @info "BEAT Metal kernel inventory coverage" observed=length(observed) inventory=length(expected)
    end
end
