# Frequent first-request specializations from real off/xy exterior workers.
# Captured with Julia 1.12.6 and the pinned Metal stack. Compile types only;
# never construct fake GPU buffers or launch an engine kernel during a build.
# Keep the dependency internals under Metal's own module bindings.
function metal_channel_task_wrapper_type()
    # Channel's task captures these fields, but its generated name changes
    # between Julia patch releases. Resolve the type rather than its number.
    wrappers = Set{UnionAll}()
    for name in names(Base; all=true)
        isdefined(Base, name) || continue
        value = getfield(Base, name)
        value isa UnionAll || continue
        T = Base.unwrap_unionall(value)
        if T isa DataType && T <: Function && fieldnames(T) == (:func, :chnl)
            push!(wrappers, value)
        end
    end
    return only(wrappers)
end

# Resolve driver closures by captured fields, never compiler-generated numbers.
# Fail on ambiguity rather than silently precompiling an unrelated closure.
function compiled_driver_closure_type(fields)
    matches = Any[]
    for name in names(@__MODULE__; all=true)
        isdefined(@__MODULE__, name) || continue
        value = getfield(@__MODULE__, name)
        value isa UnionAll || value isa DataType || continue
        T = Base.unwrap_unionall(value)
        T <: Function && fieldnames(T) == fields && push!(matches, value)
    end
    return only(matches)
end

function metal_runtime_signatures()
    channel_task_wrapper = metal_channel_task_wrapper_type()
    producer = compiled_driver_closure_type((:system, :metal_fused_kwargs, :frequencies_hz,
        :base_rule, :dp0_space, :p1_space, :excitations, :mesh, :density, :sound_speed, :FloatType))
    neumann = compiled_driver_closure_type((:omega, :mesh, :density))
    field_values = compiled_driver_closure_type((:mesh, :backend, :selected_field_cache, :wavenumber, :points))
    # The keyword implementation also has a patch-dependent generated name.
    metal_kernel_keyword_body = typeof(Base.bodyfunction(which(Tuple{Metal.HostKernel})))
    signatures = [
        Tuple{typeof(BeatEngineCompiledMetalBundle.BeatEngineContract.validate_worker_submission), JSON.Object{String, Any}},
        Tuple{typeof(BeatEngineCompiledMetalBundle.BeatEngineWorkerCleanup.cleanup_options), JSON.Object{String, Any}},
        Tuple{Type{Base.Generator{I, F} where F where I}, BeatEngineCompiledMetalBundle.BeatEngineWorkerCleanup.var"#cleanup_options##0#cleanup_options##1", Base.KeySet{Any, Base.Dict{Any, Any}}},
        Tuple{typeof(Base.all), Base.Generator{Base.KeySet{Any, Base.Dict{Any, Any}}, BeatEngineCompiledMetalBundle.BeatEngineWorkerCleanup.var"#cleanup_options##0#cleanup_options##1"}},
        Tuple{typeof(Core.kwcall), NamedTuple{(:event_mode,), Tuple{Bool}}, typeof(BeatEngineCompiledMetalBundle.solve_request), JSON.Object{String, Any}},
        Tuple{Type{BeatEngineCompiledMetalBundle.BeatEngineCore.MetalRegularAssemblyCache{Float32, Nothing}}, Nothing, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 1, Metal.PrivateStorage}, Metal.MtlArray{Float32, 3, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 2, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Array{Int64, 1}, Array{Int64, 1}, Int64, Int64, Int64, Int64, Symbol, Array{Union{}, 1}, Array{BeatEngineCompiledMetalBundle.BeatEngineCore.MetalSingularCorrectionCache{Float32}, 1}, Int64, Base.RefValue{Any}, Base.RefValue{Any}},
        Tuple{Metal.MTL.var"##MTLBuffer#3", Bool, Type{Metal.SharedStorage}, Metal.MTL.MTLResourceOptions, Metal.MTL.MTLResourceOptions, Type{Metal.MTL.MTLBuffer}, Metal.MTL.MTLDevice, Int64, Ptr{Base.Complex{Float32}}},
        Tuple{typeof(BeatEngineCompiledMetalBundle.BeatEngineCore.start_sweep_assembly_pipeline), producer{NamedTuple{(:device_cache, :singular_cache, :device_singular_cache, :identity_cache, :singular_order, :symmetry_mode), Tuple{BeatEngineCompiledMetalBundle.BeatEngineCore.MetalRegularAssemblyCache{Float32, Nothing}, BeatEngineCompiledMetalBundle.BeatEngineCore.SingularCorrectionCache{Float32}, BeatEngineCompiledMetalBundle.BeatEngineCore.MetalSingularCorrectionCache{Float32}, BeatEngineCompiledMetalBundle.BeatEngineCore.MetalFusedIdentityCache{BeatEngineCompiledMetalBundle.BeatEngineCore.MetalSparseScatterCache{Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}}, SparseArrays.SparseMatrixCSC{Base.Complex{Float32}, Int64}}, Int64, Symbol}}, Array{Any, 1}, BeatEngineCompiledMetalBundle.BeatEngineCore.TriangleRule{Float32}, BeatEngineCompiledMetalBundle.BeatEngineCore.DP0Space, BeatEngineCompiledMetalBundle.BeatEngineCore.P1Space, Array{NamedTuple{names, T} where T<:Tuple where names, 1}, BeatEngineCompiledMetalBundle.BeatEngineCore.BoundaryMesh{Float32}, Float32, Float32, Type{Float32}}, Int64, Int64, typeof(release_exterior_metal_system)},
        Tuple{channel_task_wrapper{BeatEngineCompiledMetalBundle.BeatEngineCore.var"#start_sweep_assembly_pipeline##0#start_sweep_assembly_pipeline##1"{producer{NamedTuple{(:device_cache, :singular_cache, :device_singular_cache, :identity_cache, :singular_order, :symmetry_mode), Tuple{BeatEngineCompiledMetalBundle.BeatEngineCore.MetalRegularAssemblyCache{Float32, Nothing}, BeatEngineCompiledMetalBundle.BeatEngineCore.SingularCorrectionCache{Float32}, BeatEngineCompiledMetalBundle.BeatEngineCore.MetalSingularCorrectionCache{Float32}, BeatEngineCompiledMetalBundle.BeatEngineCore.MetalFusedIdentityCache{BeatEngineCompiledMetalBundle.BeatEngineCore.MetalSparseScatterCache{Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}}, SparseArrays.SparseMatrixCSC{Base.Complex{Float32}, Int64}}, Int64, Symbol}}, Array{Any, 1}, BeatEngineCompiledMetalBundle.BeatEngineCore.TriangleRule{Float32}, BeatEngineCompiledMetalBundle.BeatEngineCore.DP0Space, BeatEngineCompiledMetalBundle.BeatEngineCore.P1Space, Array{NamedTuple{names, T} where T<:Tuple where names, 1}, BeatEngineCompiledMetalBundle.BeatEngineCore.BoundaryMesh{Float32}, Float32, Float32, Type{Float32}}, typeof(release_exterior_metal_system), Base.Threads.Atomic{Bool}, Int64}, Base.Channel{Tuple{Int64, Any}}}},
        Tuple{Type{Base.Generator{I, F} where F where I}, neumann{Float32, BeatEngineCompiledMetalBundle.BeatEngineCore.BoundaryMesh{Float32}, Float32}, Array{NamedTuple{names, T} where T<:Tuple where names, 1}},
        Tuple{typeof(Base.collect), Base.Generator{Array{NamedTuple{names, T} where T<:Tuple where names, 1}, neumann{Float32, BeatEngineCompiledMetalBundle.BeatEngineCore.BoundaryMesh{Float32}, Float32}}},
        Tuple{neumann{Float32, BeatEngineCompiledMetalBundle.BeatEngineCore.BoundaryMesh{Float32}, Float32}, NamedTuple{(:port_id, :component_id, :tags, :amplitudes), Tuple{String, String, Array{Int64, 1}, Array{Float32, 1}}}},
        Tuple{typeof(Base.fill!), Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Base.Complex{Float32}},
        Tuple{typeof(Base.map), typeof(Metal.mtlconvert), Tuple{Metal.KernelAbstractions.CompilerMetadata{Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicCheck, Nothing, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Metal.KernelAbstractions.NDIteration.NDRange{1, Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicSize, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}}}, Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Base.Complex{Float32}}},
        Tuple{typeof(Core.kwcall), NamedTuple{(:threads, :groups), Tuple{Int64, Int64}}, Metal.HostKernel{Metal.GPUArrays.var"#gpu_fill_kernel!#gpu_fill_kernel!##0", Tuple{Metal.KernelAbstractions.CompilerMetadata{Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicCheck, Nothing, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Metal.KernelAbstractions.NDIteration.NDRange{1, Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicSize, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}}}, Metal.MtlDeviceArray{Base.Complex{Float32}, 2, 1}, Base.Complex{Float32}}}, Metal.KernelAbstractions.CompilerMetadata{Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicCheck, Nothing, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Metal.KernelAbstractions.NDIteration.NDRange{1, Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicSize, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}}}, Vararg{Any}},
        Tuple{typeof(Metal.encode_arguments!), Metal.MTL.MTLComputeCommandEncoder, Metal.HostKernel{Metal.GPUArrays.var"#gpu_fill_kernel!#gpu_fill_kernel!##0", Tuple{Metal.KernelAbstractions.CompilerMetadata{Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicCheck, Nothing, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Metal.KernelAbstractions.NDIteration.NDRange{1, Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicSize, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}}}, Metal.MtlDeviceArray{Base.Complex{Float32}, 2, 1}, Base.Complex{Float32}}}, Metal.KernelState, Metal.GPUArrays.var"#gpu_fill_kernel!#gpu_fill_kernel!##0", Metal.KernelAbstractions.CompilerMetadata{Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicCheck, Nothing, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Metal.KernelAbstractions.NDIteration.NDRange{1, Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicSize, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}}}, Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Base.Complex{Float32}},
        Tuple{typeof(Base.append!), Array{Any, 1}, Tuple{Metal.GPUArrays.var"#gpu_fill_kernel!#gpu_fill_kernel!##0", Tuple{Metal.KernelAbstractions.CompilerMetadata{Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicCheck, Nothing, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Metal.KernelAbstractions.NDIteration.NDRange{1, Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicSize, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}}}, Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Base.Complex{Float32}}}},
        Tuple{typeof(Base.getproperty), BeatEngineCompiledMetalBundle.BeatEngineCore.MetalFusedGatherTables, Symbol},
        Tuple{typeof(Base.map), typeof(Metal.mtlconvert), Tuple{Metal.KernelAbstractions.CompilerMetadata{Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicCheck, Nothing, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Metal.KernelAbstractions.NDIteration.NDRange{1, Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicSize, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}}}, Metal.MtlArray{Base.Complex{Float32}, 3, Metal.PrivateStorage}, Base.Complex{Float32}}},
        Tuple{typeof(Core.kwcall), NamedTuple{(:threads, :groups), Tuple{Int64, Int64}}, Metal.HostKernel{Metal.GPUArrays.var"#gpu_fill_kernel!#gpu_fill_kernel!##0", Tuple{Metal.KernelAbstractions.CompilerMetadata{Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicCheck, Nothing, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Metal.KernelAbstractions.NDIteration.NDRange{1, Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicSize, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}}}, Metal.MtlDeviceArray{Base.Complex{Float32}, 3, 1}, Base.Complex{Float32}}}, Metal.KernelAbstractions.CompilerMetadata{Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicCheck, Nothing, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Metal.KernelAbstractions.NDIteration.NDRange{1, Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicSize, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}}}, Vararg{Any}},
        Tuple{metal_kernel_keyword_body, Int64, Int64, Nothing, Bool, Metal.HostKernel{Metal.GPUArrays.var"#gpu_fill_kernel!#gpu_fill_kernel!##0", Tuple{Metal.KernelAbstractions.CompilerMetadata{Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicCheck, Nothing, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Metal.KernelAbstractions.NDIteration.NDRange{1, Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicSize, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}}}, Metal.MtlDeviceArray{Base.Complex{Float32}, 3, 1}, Base.Complex{Float32}}}, Metal.KernelAbstractions.CompilerMetadata{Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicCheck, Nothing, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Metal.KernelAbstractions.NDIteration.NDRange{1, Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicSize, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}}}, Vararg{Any}},
        Tuple{typeof(Metal.encode_arguments!), Metal.MTL.MTLComputeCommandEncoder, Metal.HostKernel{Metal.GPUArrays.var"#gpu_fill_kernel!#gpu_fill_kernel!##0", Tuple{Metal.KernelAbstractions.CompilerMetadata{Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicCheck, Nothing, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Metal.KernelAbstractions.NDIteration.NDRange{1, Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicSize, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}}}, Metal.MtlDeviceArray{Base.Complex{Float32}, 3, 1}, Base.Complex{Float32}}}, Metal.KernelState, Metal.GPUArrays.var"#gpu_fill_kernel!#gpu_fill_kernel!##0", Metal.KernelAbstractions.CompilerMetadata{Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicCheck, Nothing, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Metal.KernelAbstractions.NDIteration.NDRange{1, Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicSize, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}}}, Metal.MtlArray{Base.Complex{Float32}, 3, Metal.PrivateStorage}, Base.Complex{Float32}},
        Tuple{typeof(Base.append!), Array{Any, 1}, Tuple{Metal.GPUArrays.var"#gpu_fill_kernel!#gpu_fill_kernel!##0", Tuple{Metal.KernelAbstractions.CompilerMetadata{Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicCheck, Nothing, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Metal.KernelAbstractions.NDIteration.NDRange{1, Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicSize, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}}}, Metal.MtlArray{Base.Complex{Float32}, 3, Metal.PrivateStorage}, Base.Complex{Float32}}}},
        Tuple{typeof(Base.map), typeof(Metal.mtlconvert), Tuple{Metal.MtlArray{Float32, 1, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 1, Metal.PrivateStorage}, Metal.MtlArray{Float32, 3, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Int32, Int32, Int32, Int32, Float32, Float32, Int32, Base.Val{6}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Int32, Vararg{Float32, 6}}},
        Tuple{typeof(Metal.encode_arguments!), Metal.MTL.MTLComputeCommandEncoder, Metal.HostKernel{typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_fused_pair_blocks_kernel!), Tuple{Metal.MtlDeviceArray{Float32, 1, 1}, Metal.MtlDeviceArray{Float32, 2, 1}, Metal.MtlDeviceArray{Float32, 2, 1}, Metal.MtlDeviceArray{Float32, 1, 1}, Metal.MtlDeviceArray{Int32, 2, 1}, Metal.MtlDeviceArray{Float32, 2, 1}, Metal.MtlDeviceArray{Float32, 2, 1}, Metal.MtlDeviceArray{Float32, 1, 1}, Metal.MtlDeviceArray{Float32, 3, 1}, Metal.MtlDeviceArray{Int32, 1, 1}, Int32, Int32, Int32, Int32, Float32, Float32, Int32, Base.Val{6}, Metal.MtlDeviceArray{Int32, 1, 1}, Metal.MtlDeviceArray{Int32, 1, 1}, Int32, Vararg{Float32, 6}}}, Metal.KernelState, typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_fused_pair_blocks_kernel!), Metal.MtlArray{Float32, 1, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 1, Metal.PrivateStorage}, Metal.MtlArray{Float32, 3, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Int32, Int32, Int32, Int32, Float32, Float32, Int32, Base.Val{6}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Int32, Vararg{Float32, 6}},
        Tuple{typeof(Base.append!), Array{Any, 1}, Tuple{typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_fused_pair_blocks_kernel!), Tuple{Metal.MtlArray{Float32, 1, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 1, Metal.PrivateStorage}, Metal.MtlArray{Float32, 3, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Int32, Int32, Int32, Int32, Float32, Float32, Int32, Base.Val{6}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Int32, Vararg{Float32, 6}}}},
        Tuple{typeof(Base.map), typeof(Metal.mtlconvert), Tuple{Metal.MtlArray{Base.Complex{Float32}, 3, Metal.PrivateStorage}, Metal.MtlArray{Float32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 2, Metal.PrivateStorage}, Vararg{Int32, 8}}},
        Tuple{typeof(Metal.encode_arguments!), Metal.MTL.MTLComputeCommandEncoder, Metal.HostKernel{typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_fused_rhs_gather_kernel!), Tuple{Metal.MtlDeviceArray{Base.Complex{Float32}, 3, 1}, Metal.MtlDeviceArray{Float32, 1, 1}, Metal.MtlDeviceArray{Int32, 1, 1}, Metal.MtlDeviceArray{Int32, 1, 1}, Metal.MtlDeviceArray{Int32, 1, 1}, Metal.MtlDeviceArray{Int32, 1, 1}, Metal.MtlDeviceArray{Int32, 1, 1}, Metal.MtlDeviceArray{Int32, 1, 1}, Metal.MtlDeviceArray{Base.Complex{Float32}, 2, 1}, Vararg{Int32, 8}}}, Metal.KernelState, typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_fused_rhs_gather_kernel!), Metal.MtlArray{Base.Complex{Float32}, 3, Metal.PrivateStorage}, Metal.MtlArray{Float32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 2, Metal.PrivateStorage}, Vararg{Int32, 8}},
        Tuple{typeof(Base.append!), Array{Any, 1}, Tuple{typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_fused_rhs_gather_kernel!), Tuple{Metal.MtlArray{Base.Complex{Float32}, 3, Metal.PrivateStorage}, Metal.MtlArray{Float32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 2, Metal.PrivateStorage}, Vararg{Int32, 8}}}},
        Tuple{typeof(Base.map), typeof(Metal.mtlconvert), Tuple{Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Metal.MtlArray{Float32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Vararg{Int32, 5}}},
        Tuple{typeof(Metal.encode_arguments!), Metal.MTL.MTLComputeCommandEncoder, Metal.HostKernel{typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_fused_lhs_gather_kernel!), Tuple{Metal.MtlDeviceArray{Base.Complex{Float32}, 2, 1}, Metal.MtlDeviceArray{Float32, 1, 1}, Metal.MtlDeviceArray{Int32, 1, 1}, Metal.MtlDeviceArray{Int32, 1, 1}, Metal.MtlDeviceArray{Int32, 1, 1}, Metal.MtlDeviceArray{Int32, 1, 1}, Metal.MtlDeviceArray{Int32, 1, 1}, Metal.MtlDeviceArray{Int32, 1, 1}, Metal.MtlDeviceArray{Int32, 1, 1}, Vararg{Int32, 5}}}, Metal.KernelState, typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_fused_lhs_gather_kernel!), Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Metal.MtlArray{Float32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Vararg{Int32, 5}},
        Tuple{typeof(Base.append!), Array{Any, 1}, Tuple{typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_fused_lhs_gather_kernel!), Tuple{Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Metal.MtlArray{Float32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Vararg{Int32, 5}}}},
        Tuple{typeof(Base.map), typeof(Metal.mtlconvert), Tuple{Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Metal.MtlArray{Base.Complex{Float32}, 3, Metal.PrivateStorage}, Int32, Int32, Int32}},
        Tuple{typeof(Metal.encode_arguments!), Metal.MTL.MTLComputeCommandEncoder, Metal.HostKernel{typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_fused_rhs_reduce_kernel!), Tuple{Metal.MtlDeviceArray{Base.Complex{Float32}, 2, 1}, Metal.MtlDeviceArray{Base.Complex{Float32}, 3, 1}, Int32, Int32, Int32}}, Metal.KernelState, typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_fused_rhs_reduce_kernel!), Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Metal.MtlArray{Base.Complex{Float32}, 3, Metal.PrivateStorage}, Int32, Int32, Int32},
        Tuple{typeof(Base.append!), Array{Any, 1}, Tuple{typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_fused_rhs_reduce_kernel!), Tuple{Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Metal.MtlArray{Base.Complex{Float32}, 3, Metal.PrivateStorage}, Int32, Int32, Int32}}},
        Tuple{typeof(Base.length), Metal.MtlArray{Float32, 1, Metal.PrivateStorage}},
        Tuple{typeof(Base.fill!), Metal.MtlArray{Base.Complex{Float32}, 2, Metal.PrivateStorage}, Base.Complex{Float32}},
        Tuple{typeof(Base.map), typeof(Metal.mtlconvert), Tuple{Metal.KernelAbstractions.CompilerMetadata{Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicCheck, Nothing, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Metal.KernelAbstractions.NDIteration.NDRange{1, Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicSize, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}}}, Metal.MtlArray{Base.Complex{Float32}, 2, Metal.PrivateStorage}, Base.Complex{Float32}}},
        Tuple{typeof(Metal.encode_arguments!), Metal.MTL.MTLComputeCommandEncoder, Metal.HostKernel{Metal.GPUArrays.var"#gpu_fill_kernel!#gpu_fill_kernel!##0", Tuple{Metal.KernelAbstractions.CompilerMetadata{Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicCheck, Nothing, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Metal.KernelAbstractions.NDIteration.NDRange{1, Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicSize, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}}}, Metal.MtlDeviceArray{Base.Complex{Float32}, 2, 1}, Base.Complex{Float32}}}, Metal.KernelState, Metal.GPUArrays.var"#gpu_fill_kernel!#gpu_fill_kernel!##0", Metal.KernelAbstractions.CompilerMetadata{Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicCheck, Nothing, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Metal.KernelAbstractions.NDIteration.NDRange{1, Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicSize, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}}}, Metal.MtlArray{Base.Complex{Float32}, 2, Metal.PrivateStorage}, Base.Complex{Float32}},
        Tuple{typeof(Base.append!), Array{Any, 1}, Tuple{Metal.GPUArrays.var"#gpu_fill_kernel!#gpu_fill_kernel!##0", Tuple{Metal.KernelAbstractions.CompilerMetadata{Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicCheck, Nothing, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Metal.KernelAbstractions.NDIteration.NDRange{1, Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicSize, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}}}, Metal.MtlArray{Base.Complex{Float32}, 2, Metal.PrivateStorage}, Base.Complex{Float32}}}},
        Tuple{typeof(Base.map), typeof(Metal.mtlconvert), Tuple{Metal.MtlArray{Base.Complex{Float32}, 2, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 2, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Float32, 1, Metal.PrivateStorage}, Metal.MtlArray{Float32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 1, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Float32, Float32, Int32, Int32, Int32, Int32, Vararg{Float32, 6}}},
        Tuple{typeof(Base.map), typeof(Metal.mtlconvert), Tuple{Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Metal.MtlArray{Base.Complex{Float32}, 2, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Int64, Int64, Int64}},
        Tuple{typeof(Metal.encode_arguments!), Metal.MTL.MTLComputeCommandEncoder, Metal.HostKernel{typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_singular_entry_gather_kernel!), Tuple{Metal.MtlDeviceArray{Base.Complex{Float32}, 2, 1}, Metal.MtlDeviceArray{Base.Complex{Float32}, 2, 1}, Metal.MtlDeviceArray{Int32, 1, 1}, Metal.MtlDeviceArray{Int32, 1, 1}, Metal.MtlDeviceArray{Int32, 1, 1}, Int64, Int64, Int64}}, Metal.KernelState, typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_singular_entry_gather_kernel!), Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Metal.MtlArray{Base.Complex{Float32}, 2, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Int64, Int64, Int64},
        Tuple{typeof(Base.append!), Array{Any, 1}, Tuple{typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_singular_entry_gather_kernel!), Tuple{Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Metal.MtlArray{Base.Complex{Float32}, 2, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Int64, Int64, Int64}}},
        Tuple{typeof(Base.map), typeof(Metal.mtlconvert), Tuple{Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Metal.MtlArray{Base.Complex{Float32}, 2, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 2, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Vararg{Int64, 6}}},
        Tuple{typeof(Metal.encode_arguments!), Metal.MTL.MTLComputeCommandEncoder, Metal.HostKernel{typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_singular_rhs_gather_kernel!), Tuple{Metal.MtlDeviceArray{Base.Complex{Float32}, 2, 1}, Metal.MtlDeviceArray{Base.Complex{Float32}, 2, 1}, Metal.MtlDeviceArray{Base.Complex{Float32}, 2, 1}, Metal.MtlDeviceArray{Int32, 1, 1}, Metal.MtlDeviceArray{Int32, 1, 1}, Metal.MtlDeviceArray{Int32, 1, 1}, Metal.MtlDeviceArray{Int32, 1, 1}, Vararg{Int64, 6}}}, Metal.KernelState, typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_singular_rhs_gather_kernel!), Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Metal.MtlArray{Base.Complex{Float32}, 2, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 2, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Vararg{Int64, 6}},
        Tuple{typeof(Base.append!), Array{Any, 1}, Tuple{typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_singular_rhs_gather_kernel!), Tuple{Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Metal.MtlArray{Base.Complex{Float32}, 2, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 2, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Vararg{Int64, 6}}}},
        Tuple{typeof(Base.map), typeof(Metal.mtlconvert), Tuple{Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Int64, Int64, Base.Complex{Float32}, Bool}},
        Tuple{typeof(Metal.encode_arguments!), Metal.MTL.MTLComputeCommandEncoder, Metal.HostKernel{typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_sparse_scatter_kernel!), Tuple{Metal.MtlDeviceArray{Base.Complex{Float32}, 2, 1}, Metal.MtlDeviceArray{Int32, 1, 1}, Metal.MtlDeviceArray{Int32, 1, 1}, Metal.MtlDeviceArray{Base.Complex{Float32}, 1, 1}, Int64, Int64, Base.Complex{Float32}, Bool}}, Metal.KernelState, typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_sparse_scatter_kernel!), Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Int64, Int64, Base.Complex{Float32}, Bool},
        Tuple{typeof(Base.append!), Array{Any, 1}, Tuple{typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_sparse_scatter_kernel!), Tuple{Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Int64, Int64, Base.Complex{Float32}, Bool}}},
        Tuple{typeof(Base.Broadcast.broadcasted), typeof(Base.:(+)), Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Metal.MtlArray{Base.Complex{Float32}, 2, Metal.PrivateStorage}},
        Tuple{typeof(Base.Broadcast.materialize!), Metal.MtlArrayStyle{2, Metal.SharedStorage}, Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Base.Broadcast.Broadcasted{Metal.MtlArrayStyle{2, Metal.SharedStorage}, Nothing, typeof(Base.:(+)), Tuple{Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Metal.MtlArray{Base.Complex{Float32}, 2, Metal.PrivateStorage}}}},
        Tuple{typeof(Metal.encode_arguments!), Metal.MTL.MTLComputeCommandEncoder, Metal.HostKernel{Metal.var"#broadcast_2d#_copyto!##2", Tuple{Metal.MtlDeviceArray{Base.Complex{Float32}, 2, 1}, Base.Broadcast.Broadcasted{Metal.MtlArrayStyle{2, Metal.SharedStorage}, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}, typeof(Base.:(+)), Tuple{Base.Broadcast.Extruded{Metal.MtlDeviceArray{Base.Complex{Float32}, 2, 1}, Tuple{Bool, Bool}, Tuple{Int64, Int64}}, Base.Broadcast.Extruded{Metal.MtlDeviceArray{Base.Complex{Float32}, 2, 1}, Tuple{Bool, Bool}, Tuple{Int64, Int64}}}}}}, Metal.KernelState, Metal.var"#broadcast_2d#_copyto!##2", Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Base.Broadcast.Broadcasted{Metal.MtlArrayStyle{2, Metal.SharedStorage}, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}, typeof(Base.:(+)), Tuple{Base.Broadcast.Extruded{Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Tuple{Bool, Bool}, Tuple{Int64, Int64}}, Base.Broadcast.Extruded{Metal.MtlArray{Base.Complex{Float32}, 2, Metal.PrivateStorage}, Tuple{Bool, Bool}, Tuple{Int64, Int64}}}}},
        Tuple{typeof(Base.append!), Array{Any, 1}, Tuple{Metal.var"#broadcast_2d#_copyto!##2", Tuple{Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Base.Broadcast.Broadcasted{Metal.MtlArrayStyle{2, Metal.SharedStorage}, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}, typeof(Base.:(+)), Tuple{Base.Broadcast.Extruded{Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Tuple{Bool, Bool}, Tuple{Int64, Int64}}, Base.Broadcast.Extruded{Metal.MtlArray{Base.Complex{Float32}, 2, Metal.PrivateStorage}, Tuple{Bool, Bool}, Tuple{Int64, Int64}}}}}}},
        Tuple{typeof(Base.put!), Base.Channel{Tuple{Int64, Any}}, Tuple{Int64, NamedTuple{(:system, :k, :assembly_s), Tuple{NamedTuple{(:matrix, :rhs, :regular_pairs, :singular_pairs, :image_singular_pairs, :drive_count, :on_gpu, :gpu_backend, :assembly_mode), Tuple{Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Int64, Int64, Int64, Int64, Bool, Symbol, Symbol}}, Float32, Float64}}}},
        Tuple{typeof(Base.getproperty), NamedTuple{(:system, :k, :assembly_s), Tuple{NamedTuple{(:matrix, :rhs, :regular_pairs, :singular_pairs, :image_singular_pairs, :drive_count, :on_gpu, :gpu_backend, :assembly_mode), Tuple{Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Metal.MtlArray{Base.Complex{Float32}, 2, Metal.SharedStorage}, Int64, Int64, Int64, Int64, Bool, Symbol, Symbol}}, Float32, Float64}}, Symbol},
        Tuple{Type{Base.Generator{I, F} where F where I}, field_values{BeatEngineCompiledMetalBundle.BeatEngineCore.BoundaryMesh{Float32}, Symbol, BeatEngineCompiledMetalBundle.BeatEngineCore.MetalFieldEvaluationCache{Float32}, Float32, Array{StaticArrays.StaticArraysCore.SArray{Tuple{3}, Float32, 1, 3}, 1}}, Base.Iterators.Zip{Tuple{Array{Array{Base.Complex{Float32}, 1}, 1}, Array{Array{Base.Complex{Float32}, 1}, 1}}}},
        Tuple{typeof(Base.collect), Base.Generator{Base.Iterators.Zip{Tuple{Array{Array{Base.Complex{Float32}, 1}, 1}, Array{Array{Base.Complex{Float32}, 1}, 1}}}, field_values{BeatEngineCompiledMetalBundle.BeatEngineCore.BoundaryMesh{Float32}, Symbol, BeatEngineCompiledMetalBundle.BeatEngineCore.MetalFieldEvaluationCache{Float32}, Float32, Array{StaticArrays.StaticArraysCore.SArray{Tuple{3}, Float32, 1, 3}, 1}}}},
        Tuple{typeof(Base.fill!), Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Base.Complex{Float32}},
        Tuple{typeof(Base.map), typeof(Metal.mtlconvert), Tuple{Metal.KernelAbstractions.CompilerMetadata{Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicCheck, Nothing, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Metal.KernelAbstractions.NDIteration.NDRange{1, Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicSize, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}}}, Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Base.Complex{Float32}}},
        Tuple{typeof(Core.kwcall), NamedTuple{(:threads, :groups), Tuple{Int64, Int64}}, Metal.HostKernel{Metal.GPUArrays.var"#gpu_fill_kernel!#gpu_fill_kernel!##0", Tuple{Metal.KernelAbstractions.CompilerMetadata{Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicCheck, Nothing, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Metal.KernelAbstractions.NDIteration.NDRange{1, Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicSize, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}}}, Metal.MtlDeviceArray{Base.Complex{Float32}, 1, 1}, Base.Complex{Float32}}}, Metal.KernelAbstractions.CompilerMetadata{Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicCheck, Nothing, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Metal.KernelAbstractions.NDIteration.NDRange{1, Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicSize, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}}}, Vararg{Any}},
        Tuple{typeof(Metal.encode_arguments!), Metal.MTL.MTLComputeCommandEncoder, Metal.HostKernel{Metal.GPUArrays.var"#gpu_fill_kernel!#gpu_fill_kernel!##0", Tuple{Metal.KernelAbstractions.CompilerMetadata{Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicCheck, Nothing, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Metal.KernelAbstractions.NDIteration.NDRange{1, Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicSize, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}}}, Metal.MtlDeviceArray{Base.Complex{Float32}, 1, 1}, Base.Complex{Float32}}}, Metal.KernelState, Metal.GPUArrays.var"#gpu_fill_kernel!#gpu_fill_kernel!##0", Metal.KernelAbstractions.CompilerMetadata{Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicCheck, Nothing, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Metal.KernelAbstractions.NDIteration.NDRange{1, Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicSize, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}}}, Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Base.Complex{Float32}},
        Tuple{typeof(Base.append!), Array{Any, 1}, Tuple{Metal.GPUArrays.var"#gpu_fill_kernel!#gpu_fill_kernel!##0", Tuple{Metal.KernelAbstractions.CompilerMetadata{Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicCheck, Nothing, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Metal.KernelAbstractions.NDIteration.NDRange{1, Metal.KernelAbstractions.NDIteration.DynamicSize, Metal.KernelAbstractions.NDIteration.DynamicSize, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}, Base.IteratorsMD.CartesianIndices{1, Tuple{Base.OneTo{Int64}}}}}, Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Base.Complex{Float32}}}},
        Tuple{typeof(Base.map), typeof(Metal.mtlconvert), Tuple{Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Metal.MtlArray{Float32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 2, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Int64}},
        Tuple{typeof(Metal.encode_arguments!), Metal.MTL.MTLComputeCommandEncoder, Metal.HostKernel{typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_weighted_field_sources_kernel!), Tuple{Metal.MtlDeviceArray{Base.Complex{Float32}, 1, 1}, Metal.MtlDeviceArray{Base.Complex{Float32}, 1, 1}, Metal.MtlDeviceArray{Base.Complex{Float32}, 1, 1}, Metal.MtlDeviceArray{Base.Complex{Float32}, 1, 1}, Metal.MtlDeviceArray{Float32, 1, 1}, Metal.MtlDeviceArray{Int32, 2, 1}, Metal.MtlDeviceArray{Int32, 1, 1}, Metal.MtlDeviceArray{Float32, 2, 1}, Int64}}, Metal.KernelState, typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_weighted_field_sources_kernel!), Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Metal.MtlArray{Float32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 2, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Int64},
        Tuple{typeof(Base.append!), Array{Any, 1}, Tuple{typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_weighted_field_sources_kernel!), Tuple{Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Metal.MtlArray{Float32, 1, Metal.PrivateStorage}, Metal.MtlArray{Int32, 2, Metal.PrivateStorage}, Metal.MtlArray{Int32, 1, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Int64}}},
        Tuple{typeof(Base.map), typeof(Metal.mtlconvert), Tuple{Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Float32, Vararg{Int64, 4}}},
        Tuple{typeof(Metal.encode_arguments!), Metal.MTL.MTLComputeCommandEncoder, Metal.HostKernel{typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_field_eval_chunked_kernel!), Tuple{Metal.MtlDeviceArray{Base.Complex{Float32}, 1, 1}, Metal.MtlDeviceArray{Float32, 2, 1}, Metal.MtlDeviceArray{Float32, 2, 1}, Metal.MtlDeviceArray{Float32, 2, 1}, Metal.MtlDeviceArray{Base.Complex{Float32}, 1, 1}, Metal.MtlDeviceArray{Base.Complex{Float32}, 1, 1}, Float32, Vararg{Int64, 4}}}, Metal.KernelState, typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_field_eval_chunked_kernel!), Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Float32, Vararg{Int64, 4}},
        Tuple{typeof(Base.append!), Array{Any, 1}, Tuple{typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_field_eval_chunked_kernel!), Tuple{Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Float32, 2, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Float32, Vararg{Int64, 4}}}},
        Tuple{typeof(Base.map), typeof(Metal.mtlconvert), Tuple{Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Int64, Int64}},
        Tuple{typeof(Metal.encode_arguments!), Metal.MTL.MTLComputeCommandEncoder, Metal.HostKernel{typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_field_reduce_partials_kernel!), Tuple{Metal.MtlDeviceArray{Base.Complex{Float32}, 1, 1}, Metal.MtlDeviceArray{Base.Complex{Float32}, 1, 1}, Int64, Int64}}, Metal.KernelState, typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_field_reduce_partials_kernel!), Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Int64, Int64},
        Tuple{typeof(Base.append!), Array{Any, 1}, Tuple{typeof(BeatEngineCompiledMetalBundle.BeatEngineCore._metal_field_reduce_partials_kernel!), Tuple{Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Metal.MtlArray{Base.Complex{Float32}, 1, Metal.PrivateStorage}, Int64, Int64}}},
        Tuple{typeof(Metal.device)},
        Tuple{typeof(Base.string), Metal.MTL.MTLDevice},
        Tuple{typeof(Core.kwcall), NamedTuple{(:cancelled, :free_fraction), Tuple{Bool, Nothing}}, typeof(BeatEngineCompiledMetalBundle.BeatEngineWorkerCleanup.cleanup_reason), NamedTuple{(:policy, :max_requests, :min_free_fraction), Tuple{String, Int64, Float64}}, Int64},
    ]
    # Follow the current device inventory for argument encoding and batched
    # launches as well as compile-only HostKernel calls. This includes #21's
    # packed regular/singular/field signatures, with exact storage modes.
    for (f, args) in metal_host_signatures()
        f === Core.kwcall && length(args) >= 2 && args[2] <: Metal.HostKernel || continue
        kernel = args[2]
        function_type = kernel.parameters[1]
        host_args = args[3:end]
        push!(signatures, Tuple{typeof(Metal.encode_arguments!), Metal.MTL.MTLComputeCommandEncoder,
            kernel, Metal.KernelState, function_type, host_args...})
        push!(signatures, Tuple{typeof(Base.map), typeof(Metal.mtlconvert), Tuple{host_args...}})
        push!(signatures, Tuple{typeof(Base.append!), Vector{Any}, Tuple{function_type,Tuple{host_args...}}})
    end
    return unique(signatures)
end

function precompile_metal_runtime_signatures()
    successes = 0
    failures = 0
    for (index, signature) in enumerate(metal_runtime_signatures())
        try
            precompile(signature) || error("No matching runtime method")
            successes += 1
        catch exception
            failures += 1
            @warn "BEAT Metal runtime precompile failed" index signature exception=(exception, catch_backtrace())
        end
    end
    @info "BEAT Metal runtime workload complete" compiled_signatures=successes failures
end
